### PR TITLE
remove deprecated rubies

### PR DESCRIPTION
**Pull request by phumpal**
## Pull Request Checklist

**Is this in reference to an existing issue?**

#### General

- [ ] Update Changelog following the conventions laid out  [here](https://github.com/sensu-plugins/community/blob/master/HOW_WE_CHANGELOG.md)

- [ ] Update README with any necessary configuration snippets

- [ ] Binstubs are created if needed

- [ ] RuboCop passes

- [ ] Existing tests pass

#### New Plugins

- [ ] Tests

- [ ] Add the plugin to the README

- [ ] Does it have a complete header as outlined [here](http://sensu-plugins.io/docs/developer_guidelines.html#coding-style)

### CODE REVIEW

**Comment by phumpal** [comment]
@majormoses ping

**Comment by phumpal** [comment]
@majormoses PTAL

**Review by majormoses — APPROVED** [review]
LGTM

**Comment by majormoses** [comment]
released: https://rubygems.org/gems/sensu-plugins-postgres/versions/3.0.0

**Comment by majormoses** [comment]
@phumpal sorry I have been busy at work and otherwise which have made my time available for reviewing plugins limited.

**Comment by phumpal** [comment]
@majormoses completely understandable. no worries at all.

**Pull request merged**
