### PR TITLE
adds more metrics to statsdb and statsbgwriter

### PR DESCRIPTION
**Pull request by phumpal**
#### General

- [x] Update Changelog following the conventions laid out  [here](https://github.com/sensu-plugins/community/blob/master/HOW_WE_CHANGELOG.md)

- [ ] Update README with any necessary configuration snippets

- [ ] Binstubs are created if needed

- [x] RuboCop passes

- [ ] Existing tests pass

#### New Plugins

- [ ] Tests

- [ ] Add the plugin to the README

- [ ] Does it have a complete header as outlined [here](http://sensu-plugins.io/docs/developer_guidelines.html#coding-style)

### CODE REVIEW

**Comment by majormoses** [comment]
looks like the failure is due to upstream dependencies for testing no longer supporting ruby `2.1`. While I could force it by locking the upstream dependencies these rubies are EOL when I have some time time I will remove support and testing for ruby `< 2.3`.

**Review by majormoses — COMMENTED** [review]
Can you confirm these metrics are in both versions 9 and 10?

**Comment by phumpal** [comment]
>  when I have some time time I will remove support and testing for ruby < 2.3.

Does it make sense to match what's in the main sensu repo? 

I threw together a quick PR (#57) but will wait to see where failures occur before investigating what else may need to change. Feel free to close if you get to it before me.

**Comment by phumpal** [comment]
> Can you confirm these metrics are in both versions 9 and 10?

Good point, I'll double check. 

Is this something tests should be added for?

**Comment by phumpal** [comment]
> Can you confirm these metrics are in both versions 9 and 10?

LGTM

### postgres:9.6 pg_stat_bg_writer
```
➜  sensu-plugins-postgres git:(master) docker run -it --rm --link some-postgres:postgres postgres:9.6 psql -h postgres -U postgres
Password for user postgres:
psql (9.6.10)
Type "help" for help.

postgres=# \d+ pg_stat_bgwriter
                          View "pg_catalog.pg_stat_bgwriter"
        Column         |           Type           | Modifiers | Storage | Description
-----------------------+--------------------------+-----------+---------+-------------
 checkpoints_timed     | bigint                   |           | plain   |
 checkpoints_req       | bigint                   |           | plain   |
 checkpoint_write_time | double precision         |           | plain   |
 checkpoint_sync_time  | double precision         |           | plain   |
 buffers_checkpoint    | bigint                   |           | plain   |
 buffers_clean         | bigint                   |           | plain   |
 maxwritten_clean      | bigint                   |           | plain   |
 buffers_backend       | bigint                   |           | plain   |
 buffers_backend_fsync | bigint                   |           | plain   |
 buffers_alloc         | bigint                   |           | plain   |
 stats_reset           | timestamp with time zone |           | plain   |
View definition:
 SELECT pg_stat_get_bgwriter_timed_checkpoints() AS checkpoints_timed,
    pg_stat_get_bgwriter_requested_checkpoints() AS checkpoints_req,
    pg_stat_get_checkpoint_write_time() AS checkpoint_write_time,
    pg_stat_get_checkpoint_sync_time() AS checkpoint_sync_time,
    pg_stat_get_bgwriter_buf_written_checkpoints() AS buffers_checkpoint,
    pg_stat_get_bgwriter_buf_written_clean() AS buffers_clean,
    pg_stat_get_bgwriter_maxwritten_clean() AS maxwritten_clean,
    pg_stat_get_buf_written_backend() AS buffers_backend,
    pg_stat_get_buf_fsync_backend() AS buffers_backend_fsync,
    pg_stat_get_buf_alloc() AS buffers_alloc,
    pg_stat_get_bgwriter_stat_reset_time() AS stats_reset;
```

### postgres:10 pg_stat_bgwriter
```
➜  sensu-plugins-postgres git:(master) docker run -it --rm --link new-postgres:postgres postgres:10 psql -h postgres -U postgres
Password for user postgres:
psql (10.5 (Debian 10.5-1.pgdg90+1))
Type "help" for help.

postgres=# \d+ pg_stat_bgwriter
                                    View "pg_catalog.pg_stat_bgwriter"
        Column         |           Type           | Collation | Nullable | Default | Storage | Description
-----------------------+--------------------------+-----------+----------+---------+---------+-------------
 checkpoints_timed     | bigint                   |           |          |         | plain   |
 checkpoints_req       | bigint                   |           |          |         | plain   |
 checkpoint_write_time | double precision         |           |          |         | plain   |
 checkpoint_sync_time  | double precision         |           |          |         | plain   |
 buffers_checkpoint    | bigint                   |           |          |         | plain   |
 buffers_clean         | bigint                   |           |          |         | plain   |
 maxwritten_clean      | bigint                   |           |          |         | plain   |
 buffers_backend       | bigint                   |           |          |         | plain   |
 buffers_backend_fsync | bigint                   |           |          |         | plain   |
 buffers_alloc         | bigint                   |           |          |         | plain   |
 stats_reset           | timestamp with time zone |           |          |         | plain   |
View definition:
 SELECT pg_stat_get_bgwriter_timed_checkpoints() AS checkpoints_timed,
    pg_stat_get_bgwriter_requested_checkpoints() AS checkpoints_req,
    pg_stat_get_checkpoint_write_time() AS checkpoint_write_time,
    pg_stat_get_checkpoint_sync_time() AS checkpoint_sync_time,
    pg_stat_get_bgwriter_buf_written_checkpoints() AS buffers_checkpoint,
    pg_stat_get_bgwriter_buf_written_clean() AS buffers_clean,
    pg_stat_get_bgwriter_maxwritten_clean() AS maxwritten_clean,
    pg_stat_get_buf_written_backend() AS buffers_backend,
    pg_stat_get_buf_fsync_backend() AS buffers_backend_fsync,
    pg_stat_get_buf_alloc() AS buffers_alloc,
    pg_stat_get_bgwriter_stat_reset_time() AS stats_reset;
```

**Comment by phumpal** [comment]
### postgres:9.6 pg_stat_database

```
docker run -it --rm --link some-postgres:postgres postgres:9.6 psql -h postgres -U postgres
Password for user postgres:
psql (9.6.10)
Type "help" for help.

postgres=# \d+ pg_stat_database;
                      View "pg_catalog.pg_stat_database"
     Column     |           Type           | Modifiers | Storage | Description
----------------+--------------------------+-----------+---------+-------------
 datid          | oid                      |           | plain   |
 datname        | name                     |           | plain   |
 numbackends    | integer                  |           | plain   |
 xact_commit    | bigint                   |           | plain   |
 xact_rollback  | bigint                   |           | plain   |
 blks_read      | bigint                   |           | plain   |
 blks_hit       | bigint                   |           | plain   |
 tup_returned   | bigint                   |           | plain   |
 tup_fetched    | bigint                   |           | plain   |
 tup_inserted   | bigint                   |           | plain   |
 tup_updated    | bigint                   |           | plain   |
 tup_deleted    | bigint                   |           | plain   |
 conflicts      | bigint                   |           | plain   |
 temp_files     | bigint                   |           | plain   |
 temp_bytes     | bigint                   |           | plain   |
 deadlocks      | bigint                   |           | plain   |
 blk_read_time  | double precision         |           | plain   |
 blk_write_time | double precision         |           | plain   |
 stats_reset    | timestamp with time zone |           | plain   |
View definition:
 SELECT d.oid AS datid,
    d.datname,
    pg_stat_get_db_numbackends(d.oid) AS numbackends,
    pg_stat_get_db_xact_commit(d.oid) AS xact_commit,
    pg_stat_get_db_xact_rollback(d.oid) AS xact_rollback,
    pg_stat_get_db_blocks_fetched(d.oid) - pg_stat_get_db_blocks_hit(d.oid) AS blks_read,
    pg_stat_get_db_blocks_hit(d.oid) AS blks_hit,
    pg_stat_get_db_tuples_returned(d.oid) AS tup_returned,
    pg_stat_get_db_tuples_fetched(d.oid) AS tup_fetched,
    pg_stat_get_db_tuples_inserted(d.oid) AS tup_inserted,
    pg_stat_get_db_tuples_updated(d.oid) AS tup_updated,
    pg_stat_get_db_tuples_deleted(d.oid) AS tup_deleted,
    pg_stat_get_db_conflict_all(d.oid) AS conflicts,
    pg_stat_get_db_temp_files(d.oid) AS temp_files,
    pg_stat_get_db_temp_bytes(d.oid) AS temp_bytes,
    pg_stat_get_db_deadlocks(d.oid) AS deadlocks,
    pg_stat_get_db_blk_read_time(d.oid) AS blk_read_time,
    pg_stat_get_db_blk_write_time(d.oid) AS blk_write_time,
    pg_stat_get_db_stat_reset_time(d.oid) AS stats_reset
   FROM pg_database d;
```

### postgres:10 pg_stat_database

```
docker run -it --rm --link new-postgres:postgres postgres:10 psql -h postgres -U postgres
Password for user postgres:
psql (10.5 (Debian 10.5-1.pgdg90+1))
Type "help" for help.

postgres=# \d+ pg_stat_database;
                                 View "pg_catalog.pg_stat_database"
     Column     |           Type           | Collation | Nullable | Default | Storage | Description
----------------+--------------------------+-----------+----------+---------+---------+-------------
 datid          | oid                      |           |          |         | plain   |
 datname        | name                     |           |          |         | plain   |
 numbackends    | integer                  |           |          |         | plain   |
 xact_commit    | bigint                   |           |          |         | plain   |
 xact_rollback  | bigint                   |           |          |         | plain   |
 blks_read      | bigint                   |           |          |         | plain   |
 blks_hit       | bigint                   |           |          |         | plain   |
 tup_returned   | bigint                   |           |          |         | plain   |
 tup_fetched    | bigint                   |           |          |         | plain   |
 tup_inserted   | bigint                   |           |          |         | plain   |
 tup_updated    | bigint                   |           |          |         | plain   |
 tup_deleted    | bigint                   |           |          |         | plain   |
 conflicts      | bigint                   |           |          |         | plain   |
 temp_files     | bigint                   |           |          |         | plain   |
 temp_bytes     | bigint                   |           |          |         | plain   |
 deadlocks      | bigint                   |           |          |         | plain   |
 blk_read_time  | double precision         |           |          |         | plain   |
 blk_write_time | double precision         |           |          |         | plain   |
 stats_reset    | timestamp with time zone |           |          |         | plain   |
View definition:
 SELECT d.oid AS datid,
    d.datname,
    pg_stat_get_db_numbackends(d.oid) AS numbackends,
    pg_stat_get_db_xact_commit(d.oid) AS xact_commit,
    pg_stat_get_db_xact_rollback(d.oid) AS xact_rollback,
    pg_stat_get_db_blocks_fetched(d.oid) - pg_stat_get_db_blocks_hit(d.oid) AS blks_read,
    pg_stat_get_db_blocks_hit(d.oid) AS blks_hit,
    pg_stat_get_db_tuples_returned(d.oid) AS tup_returned,
    pg_stat_get_db_tuples_fetched(d.oid) AS tup_fetched,
    pg_stat_get_db_tuples_inserted(d.oid) AS tup_inserted,
    pg_stat_get_db_tuples_updated(d.oid) AS tup_updated,
    pg_stat_get_db_tuples_deleted(d.oid) AS tup_deleted,
    pg_stat_get_db_conflict_all(d.oid) AS conflicts,
    pg_stat_get_db_temp_files(d.oid) AS temp_files,
    pg_stat_get_db_temp_bytes(d.oid) AS temp_bytes,
    pg_stat_get_db_deadlocks(d.oid) AS deadlocks,
    pg_stat_get_db_blk_read_time(d.oid) AS blk_read_time,
    pg_stat_get_db_blk_write_time(d.oid) AS blk_write_time,
    pg_stat_get_db_stat_reset_time(d.oid) AS stats_reset
   FROM pg_database d;
```

**Comment by majormoses** [comment]
@phumpal if you rebase I the tests should pass, let me know if you need help with that.

**Comment by phumpal** [comment]
> @phumpal if you rebase I the tests should pass, let me know if you need help with that.

@majormoses rebased!

**Review by majormoses — APPROVED** [review]
LGTM

**Comment by majormoses** [comment]
released: https://rubygems.org/gems/sensu-plugins-postgres/versions/2.2.0

**Pull request merged**
