### PR TITLE
Added generic debian asset to bonsai

### PR DESCRIPTION
**Pull request by VeselaHouba**
## Pull Request Checklist

**Is this in reference to an existing issue?**

#### General

- [X] Update Changelog following the conventions laid out  [here](https://github.com/sensu-plugins/community/blob/master/HOW_WE_CHANGELOG.md)

- [X] Update README with any necessary configuration snippets

- [X] Binstubs are created if needed

- [X] RuboCop passes

- [X] Existing tests pass

#### New Plugins

- [ ] Tests

- [ ] Add the plugin to the README

- [ ] Does it have a complete header as outlined [here](http://sensu-plugins.io/docs/developer_guidelines.html#coding-style)

#### Purpose
Ubuntu hosts can't run plugins

### CODE REVIEW

**Review by nixwiz — APPROVED** [review]
LGTM 👍

**Comment by lrosenman** [comment]
Any chance of getting this merged in? 
@majormoses ?

**Review by majormoses — APPROVED** [review]
LGTM

**Comment by majormoses** [comment]
@nixwiz let me know if you need any help with creating a release for this

**Comment by lrosenman** [comment]
@nixwiz, can you let me know when it's on bonsai?  -- Thanks!

**Comment by jspaleta** [comment]
@majormoses  @nixwiz 
I'm gonna take a crack and pushing a new release out with this today.

**Comment by jspaleta** [comment]
@majormoses  big snag..... travisCI.org has shutdown... we have to transition this repository.. and pretty much all of the repositories to travisCI.com I think.. have you started doing this?

**Comment by majormoses** [comment]
> @majormoses big snag..... travisCI.org has shutdown... we have to transition this repository.. and pretty much all of the repositories to travisCI.com I think.. have you started doing this?

lovely I thought everything was gonna be migrated into the travis-ci.com instances. I have not started that yet. I think we probably want to see if we can get by with actions rather than using an external system.

**Comment by majormoses** [comment]
@jspaleta I see that I have a `sensu-plugins` org over on travis-ci.com here: https://app.travis-ci.com/organizations/sensu-plugins/repositories. Do we want to sync in slack or open a new issue to figure out what our next steps are?

**Pull request merged**
