### PR TITLE
Assist in visualizing the PostgreSQL vacuum process

### PR DESCRIPTION
**Pull request by phumpal**
Use sensu to aggregate vacuum metrics from the `pg_stat_progress_vacuum` view.

Per https://www.postgresql.org/docs/12/progress-reporting.html#VACUUM-PROGRESS-REPORTING

## Pull Request Checklist

**Is this in reference to an existing issue?**

#### General

- [x] Update Changelog following the conventions laid out  [here](https://github.com/sensu-plugins/community/blob/master/HOW_WE_CHANGELOG.md)

- [ ] Update README with any necessary configuration snippets

- [ ] Binstubs are created if needed

- [x] RuboCop passes

- [x] Existing tests pass

#### New Plugins

- [x] Tests

- [ ] Add the plugin to the README

- [ ] Does it have a complete header as outlined [here](http://sensu-plugins.io/docs/developer_guidelines.html#coding-style)

### CODE REVIEW

**Comment by phumpal** [comment]
I may need to wait a day or two to accumulate a nice chart for these but will circle back when I have test results.

**Comment by phumpal** [comment]
Example output

```
staging-postgres-test-1.postgresql.vacuum.test_db.pid 24186 1591329314
staging-postgres-test-1.postgresql.vacuum.test_db.relid 154544 1591329314
staging-postgres-test-1.postgresql.vacuum.test_db.phase 2 1591329314
staging-postgres-test-1.postgresql.vacuum.test_db.heap_blks_total 82308 1591329314
staging-postgres-test-1.postgresql.vacuum.test_db.heap_blks_scanned 82308 1591329314
staging-postgres-test-1.postgresql.vacuum.test_db.heap_blks_vacuumed 0 1591329314
staging-postgres-test-1.postgresql.vacuum.test_db.index_vacuum_count 0 1591329314
staging-postgres-test-1.postgresql.vacuum.test_db.max_dead_tuples 96218052 1591329314
staging-postgres-test-1.postgresql.vacuum.test_db.num_dead_tuples 85 1591329314
```

**Comment by phumpal** [comment]
PTAL

**Comment by phumpal** [comment]
Gentle ping @majormoses @jspaleta

**Review by majormoses — APPROVED** [review]
LGTM

**Comment by majormoses** [comment]
released: https://rubygems.org/gems/sensu-plugins-postgres/versions/4.1.0

**Comment by phumpal** [comment]
Awesome. Thanks again @majormoses !

**Pull request merged**
